RAV-41 iOS interface for listening to Date (Day changes)
ravnhq/react-native-midnight pull request #1
Opened 2021-02-17 14:58 UTC by manasv

**What's new?**

- Translated ObjC parts of the Native Module to Swift
- Exposed the necessary methods to subscribe to events based on changes, and test the notifications with a manual trigger
- Updated view from RN side to use this methods
- Updated Podfile as Flipper version shipped with RN is outdated and was giving problems (Don't know if we ever use flipper or can be removed)

2021-02-17 16:25 UTC, donovanhiland requested changes

2021-02-17 16:25 UTC, donovanhiland commented on ios/Midnight.swift
> +    @objc func subscribe() {
I think we want `subscribe` and `unsubscribe` to instead be `startObserving` and `stopObserving`: https://github.com/facebook/react-native/blob/f7c209cd54cf336a8c500077537f5f10f8eda360/React/Modules/RCTEventEmitter.h#L37

I _think_ if you do it this way, then you don't have to manually call `subscribe` or `unsubscribe` on the javascript side, the event emitter handles that for you

2021-02-17 16:25 UTC, donovanhiland commented on ios/Midnight.m
> +RCT_EXTERN_METHOD(multiply:(nonnull double*)a
Can we remove all instances/references to multiply? We shouldn't need that anymore 😄

2021-02-17 17:26 UTC, nakp approved these changes

2021-02-17 20:08 UTC, merged

2021-03-12 23:08 UTC, donovanhiland commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/react-native-midnight/v/1.0.0)
- [GitHub release](https://github.com/ravnhq/react-native-midnight/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: